export * as AuthController from "./auth.controller"
export * as UserController from "./user.controller"
export * as ProductController from "./products.controller"
export * as ReviewController from "./review.controller"
export * as OrderController from "./order.controller"